user:
  outputs:
    default:
      keyfile_json:
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        auth_uri: https://accounts.google.com/o/oauth2/auth
        client_email: sensor-pipeline-hamed@sensor-data-pipeline-492507.iam.gserviceaccount.com
        client_id: '116377244423399616186'
        client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/sensor-pipeline-hamed%40sensor-data-pipeline-492507.iam.gserviceaccount.com
        private_key: '-----BEGIN PRIVATE KEY-----

          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDZsFCVXiLV78NI

          qCnh90rqNu1uSn38Ty6wYLjCe+jxPnOkhtfg1EE8tv81WQSCmtqq0BLqcHVaIzAM

          64QtkgS8XURxkNqa0ZtOfzp+QtOeP3VTcMEZz4L6C0ubrL5UGIMMH9NtqBDxNDck

          txv5cka9BEXQzRD0H0xSxaR2SQRrJPRblK9ttxvovwmnisjDhR6q2d4OCQLFcc2I

          eRcnd/WQrgSsEukZJ8QA7WafoXrt/a1DwogAx6FOgN9aZGDBU08HFA5zC/sOzbSP

          K5vQalpAvi0toHW/aE7cvVZRlurcvUFG4rOhtFJ7FGH/KeJ+X2z3hmhyKB0M/2Y9

          enKEZ0aZAgMBAAECggEAAt/2uHpFSIEBmbiK0Q6kgSJXkWDPeCENk0u7tOnRAjqa

          aV5UhIYZFHWwOiKiUh08bQwRa+IvUpDrZghINxfaEyjCKiPJF0lUXT2F5rv4MntR

          D9iJ3E7mwmmaxoQKAW9Pb74N20Fgc+cGIWh/qJQvRfjD+UV0B11Qczlj+iHtuoJ8

          rTEX+rFuRu/1/sqmI7YJUg+WjUsNlg/9NcxqN5QxwTLM8zSUONnWPTexzRImDoNW

          EahHeU0eCBq/aLUReh6fgCtiMVt2PezzTIZzbGWcv7sfPo1eSdXpfjcc9NYOlGdD

          Kf0C9pqYBpjsteKAmadb9BSHBN1/ClCRkSkWoELPgQKBgQD95UFTEGUZpIKl92II

          bJEH2N+xtSXsne4LZAZujAPl84MlXsWXwTbn9qL/FejU4lrGBDPjBBcGg1ROrbcB

          Cy8QoSqNF4VES3SX6W7xRB5VvhgnnVz3cQ7PZxn5QMMrT0ppqE/DWC5mVV9RgQBZ

          KgylURO7s4J5ybHLtdypTHeBOQKBgQDbfjtaD7Q3scDFqllHs6Ec2uCz2dE6NKed

          hzPM16vdgq22VZNKtYnmhj5Fl6NQhDMSuvGLhqVENiox47MWTUHJVFjog7T5ftFH

          /J+L+sLhEBIjPPesF5ILCATry8IGszUm0Kg/0ZD52DoTW++3ISo51xwhBOQTa6Uw

          uDoFwCnQYQKBgQCW5jXQD5N3DR6VU5WRWi1Mk6pH7Vkv66F6ZaWo+FCsz/EnOc+I

          ZU6jySORJk1ukWXQANlx2JFyzoVCCd8VoLcFVDR9DPio4YvXaecFQC4jWcrzaITD

          kA90V1vJl6Mnz4VzjJRzjqptKdpwD5LMa8B+VNS8n3Exvx2L7HfMq2TviQKBgGze

          DZ48D81YEx93wNS5mf3v6mgKb6aJG2Ic/2poxswV1weLJoV1ybJXf2eRMOXszFBL

          /SaRYEOXAhLAt8EmDK1JctfRC+B8MF2eRZxugl6TVAu6X7Yx8rQaBCbYZ6JfHMvl

          zq3oyhnCT/vuK9YPUxxhP4h5Ho8rY0Ho/o5/o73BAoGAWw4oHRQvjOSiwR3zE9Qf

          tRy7Jx1pDG/O8WGqNF6RXXj2dW9OON7urqTHkQe/vsZqsYHBxBfQvJa9J9JkmGd6

          XyZx02uvZA0um8fp+j4yiIwbtwNjiHOCh1+6WaWOwnJVVtyPM3Wq4ktYVjt4m/Ps

          dHxKJnIwcuc4c3NW+q4RMUg=

          -----END PRIVATE KEY-----

          '
        private_key_id: 714560484167f4ef9b05e6fc6605e641313ce25b
        project_id: sensor-data-pipeline-492507
        token_uri: https://oauth2.googleapis.com/token
        type: service_account
      method: service-account-json
      project: sensor-data-pipeline-492507
      schema: dbt_hkharazmi
      scopes:
      - https://www.googleapis.com/auth/bigquery
      - https://www.googleapis.com/auth/cloud-platform
      - https://www.googleapis.com/auth/drive
      - https://www.googleapis.com/auth/userinfo.email
      target_name: default
      threads: 4
      type: bigquery
  target: default
