version: 2

models:
  - name: stg_sensor

    columns:
      - name: timestamp
        tests:
          - not_null

      - name: machine_id
        tests:
          - not_null

      - name: ingestion_time
        tests:
          - not_null

      - name: machine_status
        tests:
          - accepted_values:
              values: ['NORMAL', 'BROKEN', 'RECOVERING']