version: 2

sources:
  - name: raw
    database: sensor-data-pipeline-492507
    schema: sensor_data
    tables:
      - name: sensor_raw
        # loaded_at_field: ingestion_time

        # freshness:
        #   warn_after: {count: 6, period: hour}
        #   error_after: {count: 24, period: hour}